fix(setup): handle `.pc` files in ldd check
Why: The previous implementation of the `ldd` check was not handling properly
     files with `.pc` extension, leading to unnecessary check.
	 This commit addresses this issue by including `.pc` in the list of extensions
	 that are exempt from the `ldd` check.

What:
- Added '.pc' extension to the case statement in `check_ldd` function, to skip
  `ldd` check for files ending with this extension
- Fixed the unxz command in `install_package` function to properly handle the
  filename with `.xz` extension.
  The target filename was incorrectly constructed.

diff --git a/src/setups/install_package b/src/setups/install_package
--- a/src/setups/install_package
+++ b/src/setups/install_package
@@ -112,10 +112,10 @@ function install_package() {
 
     local flag="${package_name%.rpm}.installed"
     if [[ "${package_name%.rpm}" != "${package_name}" ]]; then
-    if ! rpm2cpio "${pkgs_dir}/${package_name}" | cpio -idmv; then fatal "Unable to install '${package_name}'" 2; fi
+        if ! rpm2cpio "${pkgs_dir}/${package_name}" | cpio -idmv; then fatal "Unable to install '${package_name}'" 2; fi
     elif [[ "${package_name%.xz}" != "${package_name}" ]]; then
-        if ! xzcat "${pkgs_dir}/${package_name}" > "${name,,}"; then fatal "Unable to unxz '${package_name}'" 2; fi
-        chmod 755 "${name,,}"
+        if ! xzcat "${pkgs_dir}/${package_name}" > "${package_name%.xz,,}"; then fatal "Unable to unxz '${package_name}'" 2; fi
+        chmod 755 "${package_name%.xz,,}"
     elif [[ "${package_name%.tar.gz}" != "${package_name}" ]]; then
         if ! tar xpvf "${pkgs_dir}/${package_name}"; then fatal "Unable to untar gz '${package_name}'" 2; fi
     else
@@ -225,7 +225,7 @@ check_ldd() {
     # If the file extension is h, hpp, or similar, no need to run ldd
     local ext="${file##*.}"
     case "$ext" in
-        h|hpp|c|so|bz2|o|a|mo|gz|1.gz|LIB)
+        h|hpp|c|so|bz2|o|a|mo|gz|1.gz|LIB|pc)
             # info "'$file' is a header file; skipping ldd check"
             return 0
             ;;
