chore(bin): Fix indentation in install_package
Why:
The indentation in the `install_package` shell script was inconsistent which
made it difficult to match brackets, made edits difficult, and was visually
jarring upon first inspection.
Standardizing the indentation improves readability and maintainability.

What:
- Corrected indentation within the `install_package` shell script.
- Moved functions `mirror_system_executable`, `contains_any`, and `check_ldd` before the main function call.
- No changes in functionality, only improved formatting.

diff --git a/src/setups/install_package b/src/setups/install_package
--- a/src/setups/install_package
+++ b/src/setups/install_package
@@ -200,171 +200,171 @@ function install_package() {
 
 }
 
-list_package_content_to_mirror() {
-    local pkg_name="$1"
-    local pkg_file="${tools_pkgs}/${pkg_name}"
-    local clean_ldd=0
+    list_package_content_to_mirror() {
+        local pkg_name="$1"
+        local pkg_file="${tools_pkgs}/${pkg_name}"
+        local clean_ldd=0
 
-    if [[ ! -e "${pkg_file}" ]]; then
-        fatal "pkg_name file '${pkg_file}' not found" 1
-    fi
+        if [[ ! -e "${pkg_file}" ]]; then
+            fatal "pkg_name file '${pkg_file}' not found" 1
+        fi
 
-    local pkg_base
-    pkg_base=$(pkg_base "${package_name}")
+        local pkg_base
+        pkg_base=$(pkg_base "${package_name}")
 
-    info "Listing contents of pkg_name '${pkg_name}':"
-    if [[ "${pkg_name%.rpm}" != "${pkg_name}" ]]; then
-        # Open file descriptor 8 with the command output, ensuring the while read runs in the current shell.
-        exec 9< <(rpm2cpio "${pkg_file}" | cpio -itv)
-        while IFS= read -r line <&9 || [ -n "$line" ]; do
-            # Process each line (you can add custom processing here)
-            # info "call mirror_system_executable '${line}' with clean_ldd='${clean_ldd}'"
-            if ! mirror_system_executable "${line}"; then clean_ldd=1; fi
-        done
-        exec 9<&-
-    elif [[ "${pkg_name%.tar.gz}" != "${pkg_name}" ]]; then
-        tar tzvf "${pkg_file}" | while IFS= read -r line; do
-            # Process each line (custom processing can be added here)
-            info "tar.gz contains: ${line}"
-        done
-    elif [[ "${pkg_name%.xz}" != "${pkg_name}" ]]; then
-        # Assuming it's a tar.xz package
-        if file "${pkg_file}" | grep -qi "tar archive"; then
-            tar --xz -tzvf "${pkg_file}" | while IFS= read -r line; do
-                info "tar.xz contains: ${line}"
+        info "Listing contents of pkg_name '${pkg_name}':"
+        if [[ "${pkg_name%.rpm}" != "${pkg_name}" ]]; then
+            # Open file descriptor 8 with the command output, ensuring the while read runs in the current shell.
+            exec 9< <(rpm2cpio "${pkg_file}" | cpio -itv)
+            while IFS= read -r line <&9 || [ -n "$line" ]; do
+                # Process each line (you can add custom processing here)
+                # info "call mirror_system_executable '${line}' with clean_ldd='${clean_ldd}'"
+                if ! mirror_system_executable "${line}"; then clean_ldd=1; fi
             done
-        else
-            fatal "Unsupported xz archive type for pkg_name '${pkg_name}'" 1
-        fi
-    else
-        fatal "Unknown archive extension for pkg_name '${pkg_name}'" 11
-    fi
-
-    #info "Final clean_ldd='${clean_ldd}'"
-    if [[ "${clean_ldd}" != "0" ]]; then
-        fatal "Some files in the package '${pkg_name}' have absolute system paths or unresolved paths" 199
-    fi
-
-    mv "${tool_pkgs}/${pkg_base}.installed" "${tool_pkgs}/${pkg_base}.installed.mirrored" || fatal "Unable to rename flag file '${pkg_base}.installed' to '${tool_pkgs}/${pkg_base}.installed.mirrored'" 12
-
-}
-
-mirror_system_executable() {
-    local src_line="$1"
-    # Remove everything before the first '/' and prepend '/' (if not already)
-    local src_file="/${src_line#*/}"
-    local ret=0
-
-    # Check that src_file exists and is a regular file (not a symlink)
-    if [[ -f "${src_file}" && ! -L "${src_file}" ]]; then
-        # Construct the destination path by prefixing the current folder path.
-        # For example, for /usr/bin/unzipsfx, it will be copied to ./usr/bin/unzipsfx
-        task "Must copy '${src_file}' to mirror folder '$(pwd)'"
-        local dest_file="./${src_file#/}"  # removes leading /
-        local dest_dir
-        dest_dir=$(dirname "${dest_file}")
-        mkdir -p "${dest_dir}" || fatal "Unable to create directory '${dest_dir}'" 31
-
-        local cp_output
-        cp_output=$(cp "${src_file}" "${dest_file}" 2>&1)
-        rc=$?
-        if [ $rc -ne 0 ]; then
-            if echo "$cp_output" | grep -qi "Permission denied"; then
-                warning "Permission denied copying '${src_file}' to '${dest_file}', skipping marker creation"
-                return 0
+            exec 9<&-
+        elif [[ "${pkg_name%.tar.gz}" != "${pkg_name}" ]]; then
+            tar tzvf "${pkg_file}" | while IFS= read -r line; do
+                # Process each line (custom processing can be added here)
+                info "tar.gz contains: ${line}"
+            done
+        elif [[ "${pkg_name%.xz}" != "${pkg_name}" ]]; then
+            # Assuming it's a tar.xz package
+            if file "${pkg_file}" | grep -qi "tar archive"; then
+                tar --xz -tzvf "${pkg_file}" | while IFS= read -r line; do
+                    info "tar.xz contains: ${line}"
+                done
             else
-                fatal "Unable to copy '${src_file}' to '${dest_file}': ${cp_output}" 32
+                fatal "Unsupported xz archive type for pkg_name '${pkg_name}'" 1
             fi
-        fi
-        # Create a dummy file to indicate the file was copied
-        touch "${dest_file}.copied" || fatal "Unable to create marker file '${dest_file}.copied'" 33
-        info "Copied '${src_file}' to '${dest_file}' and created marker file '${dest_file}.copied'"
-    else
-        # info "No action: '${src_file}' either does not exist, is not a regular file, or is a symlink."
-        if [[  -f "./${src_file#/}" && ! -L "./${src_file#/}" ]]; then
-            if ! check_ldd "./${src_file#/}"; then ret=1; fi
-        fi
-    fi
-
-    return ${ret}
-}
-
-contains_any() {
-    local line="$1"
-    shift
-    for token in "$@"; do
-        if [[ "$line" == *"$token"* ]]; then
-            return 0
-        fi
-    done
-    return 1
-}
-
-check_ldd() {
-    local file="$1"
-
-    # If the file name includes ' -> ', treat it as a symlink and skip ldd check.
-    local exclude_tokens=(" -> " " => " "share/man" "share/doc" "share/licenses")
-    if contains_any "${file}" "${exclude_tokens[@]}"; then
-        return 0
-    fi
-
-    # If the file extension is h, hpp, or similar, no need to run ldd
-    local ext="${file##*.}"
-    case "$ext" in
-        h|hpp|c|so|bz2|o|a|mo|gz|1.gz|LIB|pc)
-            # info "'$file' is a header file; skipping ldd check"
-            return 0
-            ;;
-    esac
-    local output ret
-    # Run ldd and capture output and exit code.
-    output=$(ldd "$file" 2>&1)
-    ret=$?
-    if [ $ret -ne 0 ]; then
-        # If ldd failed because the file is not a dynamic executable, we're done.
-        if echo "$output" | grep -q "not a dynamic executable"; then
-            info "'$file' is not a dynamic executable: no ldd check needed"
-            return 0
         else
-            warning "ldd unexpectedly failed for '$file': '${output}'"
-            return $ret
-        fi
-    fi
-
-    # Exclude list: if a line contains any of these strings, skip further tests.
-    local exclude_tokens=("libm" "libc" "libdl" "ld-linux" "linux-vdso" "liboneagentproc")
-    while IFS= read -r line || [ -n "$line" ]; do
-        # If the line contains a '?' character, warn about an unresolved path.
-        if [[ "$line" == *"?"* ]]; then
-            warning "Unresolved path in ldd output: '$line'"
-            ret=1
-            continue
+            fatal "Unknown archive extension for pkg_name '${pkg_name}'" 11
         fi
 
-        # If the line includes any of the exclude tokens, do nothing.
-        if contains_any "$line" "${exclude_tokens[@]}"; then
-            continue
+        #info "Final clean_ldd='${clean_ldd}'"
+        if [[ "${clean_ldd}" != "0" ]]; then
+            fatal "Some files in the package '${pkg_name}' have absolute system paths or unresolved paths" 199
         fi
 
-        # Check for an absolute system path. We look for a slash prefixed word.
-        if [[ "${line}" =~ (^|[[:space:]])(/[^[:space:]]+) ]]; then
-            if [[ "${line}" =~ [[:space:]]*(/[^[:space:]]+) ]]; then
-                abs_path="${BASH_REMATCH[1]}"
-                if [[ -e "${root}${abs_path}" || -e "${root}/usr${abs_path}" ]]; then
-                    continue # Skip if the path exists
+        mv "${tool_pkgs}/${pkg_base}.installed" "${tool_pkgs}/${pkg_base}.installed.mirrored" || fatal "Unable to rename flag file '${pkg_base}.installed' to '${tool_pkgs}/${pkg_base}.installed.mirrored'" 12
+
+    }
+
+    mirror_system_executable() {
+        local src_line="$1"
+        # Remove everything before the first '/' and prepend '/' (if not already)
+        local src_file="/${src_line#*/}"
+        local ret=0
+
+        # Check that src_file exists and is a regular file (not a symlink)
+        if [[ -f "${src_file}" && ! -L "${src_file}" ]]; then
+            # Construct the destination path by prefixing the current folder path.
+            # For example, for /usr/bin/unzipsfx, it will be copied to ./usr/bin/unzipsfx
+            task "Must copy '${src_file}' to mirror folder '$(pwd)'"
+            local dest_file="./${src_file#/}"  # removes leading /
+            local dest_dir
+            dest_dir=$(dirname "${dest_file}")
+            mkdir -p "${dest_dir}" || fatal "Unable to create directory '${dest_dir}'" 31
+
+            local cp_output
+            cp_output=$(cp "${src_file}" "${dest_file}" 2>&1)
+            rc=$?
+            if [ $rc -ne 0 ]; then
+                if echo "$cp_output" | grep -qi "Permission denied"; then
+                    warning "Permission denied copying '${src_file}' to '${dest_file}', skipping marker creation"
+                    return 0
+                else
+                    fatal "Unable to copy '${src_file}' to '${dest_file}': ${cp_output}" 32
                 fi
             fi
-            # if abs_path starts with ${tools}; then continue
-            if [[ "${abs_path}" == "${tools}"* ]]; then
-                continue  # Skip if abs_path starts with ${tools}
+            # Create a dummy file to indicate the file was copied
+            touch "${dest_file}.copied" || fatal "Unable to create marker file '${dest_file}.copied'" 33
+            info "Copied '${src_file}' to '${dest_file}' and created marker file '${dest_file}.copied'"
+        else
+            # info "No action: '${src_file}' either does not exist, is not a regular file, or is a symlink."
+            if [[  -f "./${src_file#/}" && ! -L "./${src_file#/}" ]]; then
+                if ! check_ldd "./${src_file#/}"; then ret=1; fi
             fi
-            warning "Absolute system path '${abs_path}' detected (tools='${tools}') in ldd output: '$line' for file '${file}'"
-            ret=1
         fi
-    done <<< "${output}"
-    return $ret
-}
+
+        return ${ret}
+    }
+
+    contains_any() {
+        local line="$1"
+        shift
+        for token in "$@"; do
+            if [[ "$line" == *"$token"* ]]; then
+                return 0
+            fi
+        done
+        return 1
+    }
+
+    check_ldd() {
+        local file="$1"
+
+        # If the file name includes ' -> ', treat it as a symlink and skip ldd check.
+        local exclude_tokens=(" -> " " => " "share/man" "share/doc" "share/licenses")
+        if contains_any "${file}" "${exclude_tokens[@]}"; then
+            return 0
+        fi
+
+        # If the file extension is h, hpp, or similar, no need to run ldd
+        local ext="${file##*.}"
+        case "$ext" in
+            h|hpp|c|so|bz2|o|a|mo|gz|1.gz|LIB|pc)
+                # info "'$file' is a header file; skipping ldd check"
+                return 0
+                ;;
+        esac
+        local output ret
+        # Run ldd and capture output and exit code.
+        output=$(ldd "$file" 2>&1)
+        ret=$?
+        if [ $ret -ne 0 ]; then
+            # If ldd failed because the file is not a dynamic executable, we're done.
+            if echo "$output" | grep -q "not a dynamic executable"; then
+                info "'$file' is not a dynamic executable: no ldd check needed"
+                return 0
+            else
+                warning "ldd unexpectedly failed for '$file': '${output}'"
+                return $ret
+            fi
+        fi
+
+        # Exclude list: if a line contains any of these strings, skip further tests.
+        local exclude_tokens=("libm" "libc" "libdl" "ld-linux" "linux-vdso" "liboneagentproc")
+        while IFS= read -r line || [ -n "$line" ]; do
+            # If the line contains a '?' character, warn about an unresolved path.
+            if [[ "$line" == *"?"* ]]; then
+                warning "Unresolved path in ldd output: '$line'"
+                ret=1
+                continue
+            fi
+
+            # If the line includes any of the exclude tokens, do nothing.
+            if contains_any "$line" "${exclude_tokens[@]}"; then
+                continue
+            fi
+
+            # Check for an absolute system path. We look for a slash prefixed word.
+            if [[ "${line}" =~ (^|[[:space:]])(/[^[:space:]]+) ]]; then
+                if [[ "${line}" =~ [[:space:]]*(/[^[:space:]]+) ]]; then
+                    abs_path="${BASH_REMATCH[1]}"
+                    if [[ -e "${root}${abs_path}" || -e "${root}/usr${abs_path}" ]]; then
+                        continue # Skip if the path exists
+                    fi
+                fi
+                # if abs_path starts with ${tools}; then continue
+                if [[ "${abs_path}" == "${tools}"* ]]; then
+                    continue  # Skip if abs_path starts with ${tools}
+                fi
+                warning "Absolute system path '${abs_path}' detected (tools='${tools}') in ldd output: '$line' for file '${file}'"
+                ret=1
+            fi
+        done <<< "${output}"
+        return $ret
+    }
 
 # if one of the parameter is "--reconfigure", shift, and set reconfigure=true, then pass the rest to main
 main "$@"
