fix(setup): Improve package extension handling
Why: When installing a package as part of the setup process, said package is not
    always an rpm. Extract the extension instead of assuming 'rpm'.

What:
- Added a `pkg_base` function to extract the base name from package names with
  various extensions (.rpm, .tar.gz, .xz).
- Modified `install_package` to use `pkg_base` for generating flag file names.
- Modified `list_archive_content_to_mirror` to use `pkg_base` for handling flag
  files.
- Updated error codes to improve error handling and clarity.
- Improved error messages for unsupported package extension.
- Added support for .xz and .tar.gz packages.

diff --git a/src/setups/install_package b/src/setups/install_package
--- a/src/setups/install_package
+++ b/src/setups/install_package
@@ -70,6 +70,8 @@ function main() {
     # shellcheck disable=SC2154
     cd "${root}" || fatal "Unable to access pkgs_dir '${root}'" 22
 
+    local pkg_base
+    pkg_base=$(pkg_base "${package_name}")
     local i_log
     i_log="${tool}/logs/install_package.log"
     rm -f "${i_log}"
@@ -79,7 +81,7 @@ function main() {
     if ! check_flag_exists "${package_name}" "installed"; then
         ( install_package ) 2>&1 | tee -a "${i_log}"
         if check_flag_exists "${package_name}" "installed" && [[ -e "${i_log}" ]]; then
-            cat "${i_log}" > "${package_name%.rpm}.installed"
+            cat "${i_log}" > "${pkg_base}.installed"
         else
             fatal "Unable to install '${package_name}'" 28
         fi
@@ -87,14 +89,29 @@ function main() {
     if ! check_flag_exists "${package_name}" "mirrored"; then
         ( list_archive_content_to_mirror "${package_name}" ) 2>&1 | tee -a "${m_log}"
         if check_flag_exists "${package_name}" "mirrored" && [[ -e "${m_log}" ]]; then
-            echo "-------------------">> "${package_name%.rpm}.installed.mirrored"
-            cat "${m_log}" >> "${package_name%.rpm}.installed.mirrored"
+            echo "-------------------">> "${pkg_base}.installed.mirrored"
+            cat "${m_log}" >> "${pkg_base}.installed.mirrored"
         else
             fatal "Unable to mirror '${package_name}'" 29
         fi
     fi
     post_install "${package_name}"
     return $?
+}
+
+pkg_base() {
+    local pkg_base
+    # Example: extracting the package name base without its extension
+    if [[ "${package_name}" =~ \.rpm$ ]]; then
+        pkg_base="${package_name%.rpm}"
+    elif [[ "${package_name}" =~ \.tar\.gz$ ]]; then
+        pkg_base="${package_name%.tar.gz}"
+    elif [[ "${package_name}" =~ \.xz$ ]]; then
+        pkg_base="${package_name%.xz}"
+    else
+        fatal "Unsupported package extension for '${package_name}'" 99
+    fi
+    echo "${pkg_base}"
 }
 
 post_install() {
@@ -127,14 +144,16 @@ check_flag_exists() {
 
 function install_package() {
 
-    local flag="${tool_pkgs}/${package_name%.rpm}.installed"
+    local pkg_base
+    pkg_base=$(pkg_base "${package_name}")
+    local flag="${tool_pkgs}/${pkg_base}.installed"
     if [[ "${package_name%.rpm}" != "${package_name}" ]]; then
         if ! rpm2cpio "${pkgs_dir}/${package_name}" | cpio -idmv; then fatal "Unable to install '${package_name}'" 2; fi
     elif [[ "${package_name%.xz}" != "${package_name}" ]]; then
-        if ! xzcat "${pkgs_dir}/${package_name}" > "${package_name%.xz,,}"; then fatal "Unable to unxz '${package_name}'" 2; fi
+        if ! xzcat "${pkgs_dir}/${package_name}" > "${package_name%.xz,,}"; then fatal "Unable to unxz '${package_name}'" 4; fi
         chmod 755 "${package_name%.xz,,}"
     elif [[ "${package_name%.tar.gz}" != "${package_name}" ]]; then
-        if ! tar xpvf "${pkgs_dir}/${package_name}"; then fatal "Unable to untar gz '${package_name}'" 2; fi
+        if ! tar xpvf "${pkgs_dir}/${package_name}"; then fatal "Unable to untar gz '${package_name}'" 5; fi
     else
         fatal "unknown extension for archive '${package_name}'" 11
     fi
@@ -151,6 +170,9 @@ list_archive_content_to_mirror() {
     if [[ ! -e "${pkg_file}" ]]; then
         fatal "Archive file '${pkg_file}' not found" 1
     fi
+
+    local pkg_base
+    pkg_base=$(pkg_base "${package_name}")
 
     info "Listing contents of archive '${archive}':"
     if [[ "${archive%.rpm}" != "${archive}" ]]; then
@@ -185,7 +207,7 @@ list_archive_content_to_mirror() {
         fatal "Some files in the archive have absolute system paths or unresolved paths" 199
     fi
 
-    mv "${tool_pkgs}/${package_name%.rpm}.installed" "${tool_pkgs}/${package_name%.rpm}.installed.mirrored" || fatal "Unable to rename flag file '${package_name%.rpm}.installed' to '${tool_pkgs}/${package_name%.rpm}.installed.mirrored'" 12
+    mv "${tool_pkgs}/${pkg_base}.installed" "${tool_pkgs}/${pkg_base}.installed.mirrored" || fatal "Unable to rename flag file '${pkg_base}.installed' to '${tool_pkgs}/${pkg_base}.installed.mirrored'" 12
 
 }
 
