feat(echos): Add caller function to echoslog
Why: Enhance logging by including the caller function name.
This improves traceability and debugging.

What:
- Added a `caller` function to identify the caller function's name.
- Modified `ok`, `info`, `warning`, `task`, `error`, and `fatal` functions to
  include the caller's name in their output.
  The caller's name is enclosed in brackets `[]`.

diff --git a/src/echos/echoslog b/src/echos/echoslog
--- a/src/echos/echoslog
+++ b/src/echos/echoslog
@@ -14,15 +14,28 @@ if [[ "${FROM_UNIX}" != "" ]]; then
   warncols="103;30"
   errorcols="101;30"
 fi
+function caller() {
+  local i=1
+  local path
+  while [ -n "${BASH_SOURCE[$i]}" ]; do
+    path="${BASH_SOURCE[$i]}"
+    if [[ "$path" == *"/echos/"* ]]; then
+      ((i++))
+    else
+      break
+    fi
+  done
+  caller="$(basename "$path")"
+}
 function mlog() { if [[ "${2}" != "" ]]; then eval "${2}=\"\${${2}}\n\${1}\""; fi; }
 function spaces() { if [[ ${depth} -gt 0 ]]; then printf %${depth}s; fi; }
-function ok() { set +x; spaces; echo -e "\e[42;97m Ok    \e[0m: ${1}" >&3; mlog "ok: ${1}" "${2}"; set -x; }
-function info() { set +x; spaces; echo -e "\e[${infocols}m Info  \e[0m: ${1}" >&3; mlog "info: ${1}" "${2}"; set -x; }
-function warning() { set +x; spaces; echo -e "\e[${warncols}m Warn  \e[0m: ${1}" >&3; mlog "Warning: ${1}" "${2}"; set -x; }
-function task() { set +x; spaces; echo -e "\e[${infocols}m Task\e[0m\e[${warncols}m=>\e[0m: ${1}" >&3; mlog "Task: ${1}" "${2}"; set -x; }
-function error() { set +x; spaces; echo -e "\e[${errorcols}m Error \e[0m: ${1}" >&3; mlog "ERROR: ${1}" "${2}"; set -x; }
+function ok() { set +x; spaces; echo -e "\e[42;97m Ok    \e[0m: [${caller}] ${1}" >&3; mlog "ok: ${1}" "${2}"; set -x; }
+function info() { set +x; spaces; echo -e "\e[${infocols}m Info  \e[0m: [${caller}] ${1}" >&3; mlog "info: ${1}" "${2}"; set -x; }
+function warning() { set +x; spaces; echo -e "\e[${warncols}m Warn  \e[0m: [${caller}] ${1}" >&3; mlog "Warning: ${1}" "${2}"; set -x; }
+function task() { set +x; spaces; echo -e "\e[${infocols}m Task\e[0m\e[${warncols}m=>\e[0m: [${caller}] ${1}" >&3; mlog "Task: ${1}" "${2}"; set -x; }
+function error() { set +x; spaces; echo -e "\e[${errorcols}m Error \e[0m: [${caller}] ${1}" >&3; mlog "ERROR: ${1}" "${2}"; set -x; }
 # shellcheck disable=SC2317
-function fatal() { set +x; spaces; echo -e "\e[41;97m FATAL [${2}]\e[0m: ${1}" >&3; exit "${2}"; mlog "FATAL: ${1}" "${3}"; set -x; }
+function fatal() { set +x; spaces; echo -e "\e[41;97m FATAL [${2}]\e[0m: [${caller}] ${1}" >&3; exit "${2}"; mlog "FATAL: ${1}" "${3}"; set -x; }
 
 # https://stackoverflow.com/questions/2683279/how-to-detect-if-a-script-is-being-sourced
 (return 0 2>/dev/null) && sourced=1 || sourced=0
