feat(echos): display script name as prefix on echos messages

diff --git a/src/echos/echos b/src/echos/echos
--- a/src/echos/echos
+++ b/src/echos/echos
@@ -14,14 +14,27 @@ if [[ "${FROM_UNIX}" != "" ]]; then
   warncols="103;30"
   errorcols="101;30"
 fi
+function caller() {
+  local i=1
+  local path
+  while [ -n "${BASH_SOURCE[$i]}" ]; do
+    path="${BASH_SOURCE[$i]}"
+    if [[ "$path" == *"/echos/"* ]]; then
+      ((i++))
+    else
+      break
+    fi
+  done
+  caller="$(basename "$path")"
+}
 function mlog() { if [[ "${2}" != "" ]]; then eval "${2}=\"\${${2}}\n\${1}\""; fi; }
-function spaces() { if [[ ${depth} -gt 0 ]]; then printf %${depth}s; fi; }
-function ok() { spaces; echo -e "\e[42;97m Ok    \e[0m: ${1}"; mlog "ok: ${1}" "${2}"; }
-function info() { spaces; echo -e "\e[${infocols}m Info  \e[0m: ${1}"; mlog "info: ${1}" "${2}"; }
-function task() { spaces; echo -e "\e[${infocols}m Task\e[0m\e[${warncols}m=>\e[0m: ${1}"; mlog "Task: ${1}" "${2}"; }
-function warning() { spaces; echo -e "\e[${warncols}m Warn  \e[0m: ${1}"; mlog "Warning: ${1}" "${2}"; }
-function error() { spaces; echo -e "\e[${errorcols}m Error \e[0m: ${1}"; mlog "ERROR: ${1}" "${2}"; }
-function fatal() { spaces; echo -e "\e[41;97m FATAL \e[0m: ${1}"; exit "${2}"; mlog "FATAL: ${1}" "${3}"; }
+function spaces() { caller; if [[ ${depth} -gt 0 ]]; then printf %${depth}s; fi; }
+function ok() { spaces; echo -e "\e[42;97m Ok    \e[0m: [${caller}] ${1}"; mlog "ok: ${1}" "${2}"; }
+function info() { spaces; echo -e "\e[${infocols}m Info  \e[0m: [${caller}] ${1}"; mlog "info: ${1}" "${2}"; }
+function task() { spaces; echo -e "\e[${infocols}m Task\e[0m\e[${warncols}m=>\e[0m: [${caller}] ${1}"; mlog "Task: ${1}" "${2}"; }
+function warning() { spaces; echo -e "\e[${warncols}m Warn  \e[0m: [${caller}] ${1}"; mlog "Warning: ${1}" "${2}"; }
+function error() { spaces; echo -e "\e[${errorcols}m Error \e[0m: [${caller}] ${1}"; mlog "ERROR: ${1}" "${2}"; }
+function fatal() { spaces; echo -e "\e[41;97m FATAL [${2}]\e[0m: [${caller}] ${1}"; mlog "FATAL: ${1}" "${3}"; exit "${2}"; }
 
 # https://stackoverflow.com/questions/2683279/how-to-detect-if-a-script-is-being-sourced
 (return 0 2>/dev/null) && sourced=1 || sourced=0
