feat(install): rename archive to package in install scripts
Why: Improve terminology: a package is just the lib, without runtime dependencies
     or script wrapper.

What:
- Renamed `archive` function to `package` in `install` and `mpdecimal/install_functions.sh` scripts.
- Updated related variable names (e.g., `archive_name` to `package_name`).
- Adjusted messages to reflect the terminology change.

diff --git a/src/install/env/install b/src/install/env/install
--- a/src/install/env/install
+++ b/src/install/env/install
@@ -296,11 +296,11 @@ function main() {
         error "main: install failed with '${res_install}'"
         return "${res_install}"
     fi
-    archive
-    res_archive=$?
-    if [[ ${res_archive} != 0 ]]; then
-        error "main: archive failed with '${res_archive}'"
-        return "${res_archive}"
+    package
+    res_package=$?
+    if [[ ${res_package} != 0 ]]; then
+        error "main: package failed with '${res_package}'"
+        return "${res_package}"
     fi
     return $?
 }
