feat(install): add make install, with mpdecimal
Why: the generic install script now calls a tool install() to trigger if needed
     a `make install`.
	 Introduces a check for the existence and age of the `libmpdec.so` file to
	 prevent unnecessary re-installations and ensure a successful build process.

What:
- Added an 'install' function to `mpdecimal/install_functions.sh`.
- Implemented a check to see if `mpdecimal` needs to be installed.
- Integrated the 'install' function into the main build script.
- Added error handling for installation failures.
- Improved logging messages for clarity.

diff --git a/src/install/env/install b/src/install/env/install
--- a/src/install/env/install
+++ b/src/install/env/install
@@ -290,6 +290,12 @@ function main() {
         error "main: build failed with '${res_build}'"
         return "${res_build}"
     fi
+    install
+    res_install=$?
+    if [[ ${res_install} != 0 ]]; then
+        error "main: install failed with '${res_install}'"
+        return "${res_install}"
+    fi
     return $?
 }
 
