feat(install): deploy cplx-bin conditionally
Why: Deploying `cplx-bin` is now conditional, controlled by the `CPLX_BIN`
     property in the properties file.
	 This allows for more flexibility in deployments, especially in
	 containerized environments where `cplx-bin` may not be required.
	 Used to determine is a packaged lib must be copied to `tools/pkgs` or not.

What:
- Added a check for the `CPLX_BIN` property in the properties file.
- Conditionally execute the `deploy` function based on the `CPLX_BIN` value.
- Return an error if `CPLX_BIN` is not found in the properties file.

diff --git a/src/install/env/install b/src/install/env/install
--- a/src/install/env/install
+++ b/src/install/env/install
@@ -302,6 +302,19 @@ function main() {
         error "main: package failed with '${res_package}'"
         return "${res_package}"
     fi
+    get_property CPLX_BIN
+    if [[ -z "$CPLX_BIN" ]]; then
+        error "No CPLX_BIN found in the properties file '${properties_file}'"
+        return 126
+    fi
+    if [[ ! "${CPLX_BIN}" == "true" ]]; then
+        deploy
+        res_deploy=$?
+        if [[ ${res_deploy} != 0 ]]; then
+            error "main: deploy failed with '${res_deploy}'"
+            return "${res_deploy}"
+        fi
+    fi
     return $?
 }
 
