feat(install): Add mpdecimal archive step
Why: This patch adds an archive step for the mpdecimal library after installation.
     This allows for easier redistribution and management of the installed libraries.

What:
- Added an `archive` function to `src/install/env/mpdecimal/install_functions.sh`.
- This function creates a tar.gz archive of the installed mpdecimal library.
- Added a call to the tool `archive` function in `src/install/env/install`.
- Added `CPLX_ARCH_EXT` property to `src/setups/env/cplx.properties` to define
  the architecture  for the archive name.
- Improved error and informational messages.
- Conditional archive creation checks (whether the archive exists and if it's newer than the lib).

diff --git a/src/install/env/install b/src/install/env/install
--- a/src/install/env/install
+++ b/src/install/env/install
@@ -296,6 +296,12 @@ function main() {
         error "main: install failed with '${res_install}'"
         return "${res_install}"
     fi
+    archive
+    res_archive=$?
+    if [[ ${res_archive} != 0 ]]; then
+        error "main: archive failed with '${res_archive}'"
+        return "${res_archive}"
+    fi
     return $?
 }
 
